### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by rodneicouto** [c4wrd/angular2-electron-boilerplate#3]
after download and run "npm start" i get: 

src/app/app.ts(4,13): error TS2304: Cannot find name 'module'.

```
stderr: 
```

Stack:
Error: Command `tsc` failed with exit code 2
    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose](net.js:492:12)

**Comment by rodneicouto** [comment]
sorry, i have to run "typings install" after "npm i". this is not a bug.

**Comment by c4wrd** [comment]
@rodneicouto No worries, I recently pushed a few commits that tidy a few things and fully committed to RC5. Feel free to take a look!
